name: NJ Transit Departure Scraper

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every 1 minute
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pandas pytz
    
    - name: Run collect
      run: python collect.py
    
    - name: Configure Git
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
    
    - name: Commit and push if changes
      run: |
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update departure data [skip ci]" && git push)